// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace opra.itelligent.es.Models
{
    public partial class TblSolucionTsp
    {
        public int IntId { get; set; }
        public int IntIdProblema { get; set; }
        public int IntIdModelo { get; set; }
        public double DblCoste { get; set; }
        public double DblTiempo { get; set; }
        public DateTimeOffset DtmAlta { get; set; }
        public string StrSolucion { get; set; }

        public virtual TblModeloTsp IntIdModeloNavigation { get; set; }
        public virtual TblMaestraProblemaTsp IntIdProblemaNavigation { get; set; }
    }
}