// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace opra.itelligent.es.Models
{
    public partial class TblEjecucion
    {
        public TblEjecucion()
        {
            TblSolucion = new HashSet<TblSolucion>();
        }

        public int IntId { get; set; }
        public int IntIdProblema { get; set; }
        public string StrNombre { get; set; }
        public DateTime DtmAlta { get; set; }

        public virtual TblMaestraProblema IntIdProblemaNavigation { get; set; }
        public virtual ICollection<TblSolucion> TblSolucion { get; set; }
    }
}