// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace opra.itelligent.es.Models
{
    public partial class TblMaestraProblema
    {
        public TblMaestraProblema()
        {
            TblEjecucion = new HashSet<TblEjecucion>();
        }

        public int IntId { get; set; }
        public string StrNombreProblema { get; set; }
        public string StrDescripcion { get; set; }
        public int IntNumeroTrabajos { get; set; }
        public int IntNumeroMaquinas { get; set; }
        public string StrFuente { get; set; }
        public double? DblMejorSolucion { get; set; }
        public string StrBucketS3 { get; set; }
        public string StrKeyS3 { get; set; }
        public DateTime DtmAlta { get; set; }

        public virtual ICollection<TblEjecucion> TblEjecucion { get; set; }
    }
}