// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace opra.itelligent.es.Models
{
    public partial class TblMaestraProblemaTsp
    {
        public TblMaestraProblemaTsp()
        {
            TblSolucionTsp = new HashSet<TblSolucionTsp>();
        }

        public int IntId { get; set; }
        public string StrNombreProblema { get; set; }
        public string StrDescripcion { get; set; }
        public double? DblMejorSolucion { get; set; }
        public string StrBucketS3 { get; set; }
        public string StrKeyS3 { get; set; }
        public DateTime DtmAlta { get; set; }
        public string StrSolucionOptima { get; set; }

        public virtual ICollection<TblSolucionTsp> TblSolucionTsp { get; set; }
    }
}