// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace opra.itelligent.es.Models
{
    public partial class TblModeloTsp
    {
        public TblModeloTsp()
        {
            TblSolucionTsp = new HashSet<TblSolucionTsp>();
        }

        public int IntId { get; set; }
        public string StrNombre { get; set; }

        public virtual ICollection<TblSolucionTsp> TblSolucionTsp { get; set; }
    }
}