// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace opra.itelligent.es.Models
{
    public partial class TblSolucion
    {
        public int IntId { get; set; }
        public int IntIdEjecucion { get; set; }
        public string StrLinkS3 { get; set; }
        public bool BlnInicial { get; set; }
        public double DblCoste { get; set; }
        public DateTime DtmAlta { get; set; }
        public double? DblTiempo { get; set; }

        public virtual TblEjecucion IntIdEjecucionNavigation { get; set; }
    }
}